### PR TITLE
adding Sett

### PR DESCRIPTION
**Pull request by kevinsalter**

### CODE REVIEW

**Comment by ynk** [comment]
Thank you! I'll take a look at all the ID's again and will add the missing ones 😄.

**Comment by kevinsalter** [comment]
No prob! Thanks for the cool script 😎

**Comment by ynk** [comment]
No worries! We run a website for this now: [https://lookup.gg](Lookup.GG)

**Comment by kevinsalter** [comment]
Nice one! Thanks for the link

**Pull request merged**
